version: 2

models:
  - name: stg_yt_profile_stats
    description: "A starter dbt model"
    columns:
      - name: response
        description: "RAW API Response"
        tests:
          - not_null
      - name: channel_title
        description: "YouTube Channel Name"
