# Logging configuration
logging:
  version: 1.1
  formatters:
    yt-tracker:
      format: "yt-profile-stats - %(asctime)s - %(funcName)s - %(levelname)s - %(message)s"
  file:
      filename: 'logs/yt-tracker.logs'
  root:
    level: DEBUG
    handlers: [console]