
version: 2

sources:
  - name: yt_profile_stats
    schema: yt_stats
    tables:
      - name: yt_profile_stats
        identifier: yt_profile_stats
        columns:
          - name: _id
            description: Unique ID call made to Youtube API
          - name: ingested_date
            description: Date of the API call (YYYY-MM-DD)
          - name: response
            description: API Response Data
          - name: status_code
            description: API Status Code
          - name: channel_name
            description: YT Channel Name